// src/modules/counter/presentation/pages/Counter.tsx
import React from 'react';
import useCounter from '../../application/services/useReactCounter';

export default function Counter() {
  const { count, increment, decrement } = useCounter();

  return <>
    <h1>This is the Counter page</h1>
    <p>The count is {count}</p>
    <button onClick={() => increment(1)}>+</button>
    <button onClick={() => decrement(1)}>-</button>
  </>;
}

// src/modules/counter/presentation/pages/Counter.vue
<template>
  <h1>This is the Counter page</h1>
  <p>The count is {{ count }}</p>
  <button @click="increment(1)">+</button>
  <button @click="decrement(1)">-</button>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import useCounter from '../../application/services/useVueCounter';

export default defineComponent({
  name: 'Counter',
  setup() {
    const { count, increment, decrement } = useCounter();

    return {
      count,
      increment,
      decrement
    }
  }
});
</script>
