// src/modules/counter/presentation/pages/Counter.svelte
<script lang="ts">
  import { count, increment, decrement } from '../../application/services/useSvelteCounter';

  function incrementCount() {
    increment(1);
  }

  function decrementCount() {
    decrement(1);
  }
</script>

<h1>This is the Counter page</h1>
<p>The count is {$count}</p>
<button on:click={incrementCount}>+</button>
<button on:click={decrementCount}>-</button>

// src/modules/counter/presentation/pages/Counter.tsx
import React from 'react';
import useCounter from '../../application/services/useReactCounter';

export default function Counter() {
  const { count, increment, decrement } = useCounter();

  return <>
    <h1>This is the Counter page</h1>
    <p>The count is {count}</p>
    <button onClick={() => increment(1)}>+</button>
    <button onClick={() => decrement(1)}>-</button>
  </>;
}
